LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
ENTITY FULLADDER IS
    PORT (
        A : IN STD_LOGIC;
        B : IN STD_LOGIC;
        Cin : IN STD_LOGIC;
        R : OUT STD_LOGIC;
        Cout : OUT STD_LOGIC);
END FULLADDER;
ARCHITECTURE LOGICFULLADDER OF FULLADDER IS
BEGIN
    R <= A XOR B XOR Cin;
    Cout <= (A AND B) OR ((A XOR B) AND Cin);
END LOGICFULLADDER;