LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY ADDER IS
    PORT (
        A : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
        B : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
        CIN : IN STD_LOGIC;
        R : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
        COUT : OUT STD_LOGIC
    );
END ENTITY;

ARCHITECTURE ARCH OF ADDER IS

    COMPONENT FULLADDER
        PORT (
            A : IN STD_LOGIC;
            B : IN STD_LOGIC;
            CIN : IN STD_LOGIC;
            R : OUT STD_LOGIC;
            COUT : OUT STD_LOGIC
        );
    END COMPONENT;

    SIGNAL C0 : STD_LOGIC;
    SIGNAL C1 : STD_LOGIC;
    SIGNAL C2 : STD_LOGIC;
BEGIN
    F0 : FULLADDER PORT MAP(A(0), B(0), CIN, R(0), C0);
    F1 : FULLADDER PORT MAP(A(1), B(1), C0, R(1), C1);
    F2 : FULLADDER PORT MAP(A(2), B(2), C1, R(2), C2);
    F3 : FULLADDER PORT MAP(A(3), B(3), C2, R(3), COUT);
END ARCHITECTURE;