LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY Counter IS
	PORT (
		Reset : IN STD_LOGIC;
		Clock : IN STD_LOGIC;
		Enabled : IN STD_LOGIC;
		S : OUT STD_LOGIC_VECTOR(3 DOWNTO 0)
	);
END ENTITY;

ARCHITECTURE ARCH OF Counter IS

	COMPONENT REG
		PORT (
			Reset : IN STD_LOGIC;
			Clock : IN STD_LOGIC;
			Enabled : IN STD_LOGIC;
			DIN : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
			DOUT : OUT STD_LOGIC_VECTOR(3 DOWNTO 0)
		);
	END COMPONENT;

	COMPONENT ADDER
		PORT (
			A : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
			B : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
			CIN : IN STD_LOGIC;
			R : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
			COUT : OUT STD_LOGIC
		);
	END COMPONENT;

	SIGNAL DIN : STD_LOGIC_VECTOR(3 DOWNTO 0);
	SIGNAL DOUT : STD_LOGIC_VECTOR(3 DOWNTO 0) := "0000";
BEGIN
	R : REG PORT MAP(Reset, Clock, Enabled, DIN, DOUT);
	A : ADDER PORT MAP(DOUT, "0001", '0', DIN, OPEN);
	S <= DIN;
END ARCHITECTURE;