LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
ENTITY FLAGS IS
    PORT (
        A3 : IN STD_LOGIC;
        B3 : IN STD_LOGIC;
        R3 : IN STD_LOGIC;
        iCBo : IN STD_LOGIC;
        OVo : OUT STD_LOGIC;
        CBo : OUT STD_LOGIC);
END FLAGS;
ARCHITECTURE ARCH_FLAGS OF FLAGS IS
BEGIN
    OVo <= (NOT A3 AND NOT B3 AND R3) OR (A3 AND B3 AND NOT R3);
    CBo <= iCBo;
END ARCH_FLAGS;