LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY FULLADDER IS
    PORT (
        A : IN STD_LOGIC;
        B : IN STD_LOGIC;
        CIN : IN STD_LOGIC;
        R : OUT STD_LOGIC;
        COUT : OUT STD_LOGIC
    );
END ENTITY;

ARCHITECTURE ARCH OF FULLADDER IS
BEGIN
    R <= A XOR B XOR CIN;
    COUT <= (A AND B) OR ((A XOR B) AND CIN);
END ARCHITECTURE;