LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY REG IS
	PORT (
		Reset : IN STD_LOGIC;
		Clock : IN STD_LOGIC;
		Enabled : IN STD_LOGIC;
		DIN : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
		DOUT : OUT STD_LOGIC_VECTOR(3 DOWNTO 0)
	);
END ENTITY;

ARCHITECTURE ARCH OF REG IS
	COMPONENT FFD
		PORT (
			DIN : IN STD_LOGIC;
			Reset : IN STD_LOGIC;
			Clock : IN STD_LOGIC;
			Enabled : IN STD_LOGIC;
			SET : IN STD_LOGIC;
			DOUT : OUT STD_LOGIC
		);
	END COMPONENT;
BEGIN
	F0 : FFD PORT MAP(DIN(0), Reset, Clock, Enabled, '0', DOUT(0));
	F1 : FFD PORT MAP(DIN(1), Reset, Clock, Enabled, '0', DOUT(1));
	F2 : FFD PORT MAP(DIN(2), Reset, Clock, Enabled, '0', DOUT(2));
	F3 : FFD PORT MAP(DIN(3), Reset, Clock, Enabled, '0', DOUT(3));
END ARCHITECTURE;