LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;

ENTITY Mux41 IS
	PORT (
		A, B, C, D : IN STD_LOGIC;
		S : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
		M : OUT STD_LOGIC
	);
END Mux41;

ARCHITECTURE arq_mux41 OF MUX41 IS
BEGIN
	M <= A WHEN S = "00" ELSE
		B WHEN S = "01" ELSE
		C WHEN S = "10" ELSE
		D WHEN S = "11";
END ARCHITECTURE;