LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY FFD IS
	PORT (
		DIN : IN STD_LOGIC;
		Reset : IN STD_LOGIC;
		Clock : IN STD_LOGIC;
		Enabled : IN STD_LOGIC;
		SET : IN STD_LOGIC;
		DOUT : OUT STD_LOGIC
	);
END ENTITY;

ARCHITECTURE ARCH OF FFD IS
BEGIN
	DOUT <= '0' WHEN Reset = '1' ELSE
		'1' WHEN SET = '1' ELSE
		DIN WHEN rising_edge(Clock) AND Enabled = '1';
END ARCHITECTURE;